//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbConfig
    {
        public int id { get; set; }
        public string name { get; set; }
        public string yydbConfigName { get; set; }
        public string oaFormmainTab { get; set; }
        public string oaFormsonTab { get; set; }
        public Nullable<long> oaFormainId { get; set; }
        public string oaCreateName { get; set; }
        public string oachuangjinshijin { get; set; }
        public string oafaqiren { get; set; }
        public string oacompany { get; set; }
        public string oaphone { get; set; }
        public string oalAmount { get; set; }
        public string oacAmount { get; set; }
        public string oashouyibumen { get; set; }
        public string oabody_type { get; set; }
        public string oatitle { get; set; }
        public string oafinish_date { get; set; }
        public string oafaqibumen { get; set; }
        public string oacolId { get; set; }
        public string oamid { get; set; }
        public string oatype { get; set; }
    }
}
