//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Person = new HashSet<Person>();
            this.Ap_CloseBill = new HashSet<Ap_CloseBill>();
            this.Vendor = new HashSet<Vendor>();
            this.GL_accvouch = new HashSet<GL_accvouch>();
        }
    
        public string cDepCode { get; set; }
        public bool bDepEnd { get; set; }
        public string cDepName { get; set; }
        public byte iDepGrade { get; set; }
        public string cDepPerson { get; set; }
        public string cDepProp { get; set; }
        public string cDepPhone { get; set; }
        public string cDepAddress { get; set; }
        public string cDepMemo { get; set; }
        public Nullable<double> iCreLine { get; set; }
        public string cCreGrade { get; set; }
        public Nullable<int> iCreDate { get; set; }
        public string cOfferGrade { get; set; }
        public Nullable<double> iOfferRate { get; set; }
        public byte[] pubufts { get; set; }
        public bool bShop { get; set; }
        public System.Guid cDepGUID { get; set; }
        public Nullable<System.DateTime> dDepBeginDate { get; set; }
        public Nullable<System.DateTime> dDepEndDate { get; set; }
        public string vAuthorizeDoc { get; set; }
        public string vAuthorizeUnit { get; set; }
        public string cDepFax { get; set; }
        public string cDepPostCode { get; set; }
        public string cDepEmail { get; set; }
        public string cDepType { get; set; }
        public Nullable<int> bInheritDutyBasic { get; set; }
        public Nullable<int> bInheritWorkCalendar { get; set; }
        public string cDutyCode { get; set; }
        public string cRestCode { get; set; }
        public Nullable<bool> bIM { get; set; }
        public string cDepNameEn { get; set; }
        public Nullable<bool> bRetail { get; set; }
        public string cDepFullName { get; set; }
        public Nullable<int> iDepOrder { get; set; }
        public string cDepLeader { get; set; }
        public Nullable<System.DateTime> dModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ap_CloseBill> Ap_CloseBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor> Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_accvouch> GL_accvouch { get; set; }
    }
}
