//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecs_region
    {
        public short region_id { get; set; }
        public short parent_id { get; set; }
        public string region_name { get; set; }
        public int region_type { get; set; }
        public short agency_id { get; set; }
    }
}
