//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialRecords
    {
        public int id { get; set; }
        public string liushuiId { get; set; }
        public string beginFinancial { get; set; }
        public string endFinancial { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createMan { get; set; }
    }
}
