//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAtoU8DATAEntities : DbContext
    {
        public OAtoU8DATAEntities()
            : base("name=OAtoU8DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<triggerSummary> triggerSummary { get; set; }
        public virtual DbSet<producehelp> producehelp { get; set; }
        public virtual DbSet<userInfo> userInfo { get; set; }
        public virtual DbSet<contrast> contrast { get; set; }
        public virtual DbSet<MessageShow> MessageShow { get; set; }
        public virtual DbSet<PrintRecordBody> PrintRecordBody { get; set; }
        public virtual DbSet<PrintRecord> PrintRecord { get; set; }
        public virtual DbSet<ChangeBankMiddle> ChangeBankMiddle { get; set; }
        public virtual DbSet<dbConfig> dbConfig { get; set; }
        public virtual DbSet<FinancialRecords> FinancialRecords { get; set; }
        public virtual DbSet<userOATab> userOATab { get; set; }
        public virtual DbSet<yq_certificates> yq_certificates { get; set; }
        public virtual DbSet<yq_cityCode> yq_cityCode { get; set; }
        public virtual DbSet<yq_code> yq_code { get; set; }
        public virtual DbSet<yq_customerAccount> yq_customerAccount { get; set; }
        public virtual DbSet<yq_log> yq_log { get; set; }
        public virtual DbSet<yq_userAccount> yq_userAccount { get; set; }
        public virtual DbSet<yq_error> yq_error { get; set; }
        public virtual DbSet<yq_cityCode_zhaohang> yq_cityCode_zhaohang { get; set; }
        public virtual DbSet<yq_paymentRecord> yq_paymentRecord { get; set; }
        public virtual DbSet<RecordTable> RecordTable { get; set; }
        public virtual DbSet<ecs_region> ecs_region { get; set; }
        public virtual DbSet<yq_zhaohang_yhCode> yq_zhaohang_yhCode { get; set; }
    }
}
