//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class v3xEntities : DbContext
    {
        public v3xEntities()
            : base("name=v3xEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<form_enumlist> form_enumlist { get; set; }
        public virtual DbSet<form_enumvalue> form_enumvalue { get; set; }
        public virtual DbSet<col_body> col_body { get; set; }
        public virtual DbSet<v3x_affair> v3x_affair { get; set; }
        public virtual DbSet<v3x_attachment> v3x_attachment { get; set; }
        public virtual DbSet<formmain_0190> formmain_0190 { get; set; }
        public virtual DbSet<formmain_0545> formmain_0545 { get; set; }
        public virtual DbSet<formson_0191> formson_0191 { get; set; }
        public virtual DbSet<formson_0546> formson_0546 { get; set; }
        public virtual DbSet<v3x_org_department> v3x_org_department { get; set; }
        public virtual DbSet<v3x_org_member> v3x_org_member { get; set; }
        public virtual DbSet<col_summary> col_summary { get; set; }
        public virtual DbSet<formmain_0593> formmain_0593 { get; set; }
        public virtual DbSet<formson_0594> formson_0594 { get; set; }
    }
}
