//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFromework
{
    using System;
    using System.Collections.Generic;
    
    public partial class yq_customerAccount
    {
        public int id { get; set; }
        public string acctNo { get; set; }
        public string acctName { get; set; }
        public string acctBankName { get; set; }
        public string acctRecCode { get; set; }
        public string acctProvinceCode { get; set; }
        public string acctCityName { get; set; }
        public string iDNo { get; set; }
        public Nullable<int> iDType { get; set; }
    }
}
